name: ""
on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "55 02 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update Packages
        run: |
          nix run nixpkgs#nix-update -- --flake .#packages --build --commit
      - name: Push to repo
        run: git push
